Finished implementing the error checking and handling for empty or invalid values in the install-mozilla-app.conf file.

diff --git a/install-mozilla-app b/install-mozilla-app
--- a/install-mozilla-app
+++ b/install-mozilla-app
@@ -5,8 +5,8 @@
 #
 # This software is released under the Revised BSD License.
 # 
-# Copyright (c) 2015, Ryan Chapin, http:www.ryanchapin.com	      
-# All rights reserved.					      
+# Copyright (c) 2015, Ryan Chapin, http:www.ryanchapin.com         
+# All rights reserved.                     
 #                                                                     
 # Redistribution  and  use  in  source  and binary forms, with or
 # without modification, are permitted provided that the following
@@ -48,17 +48,85 @@
 # name:     install-mozilla-app
 # author:   Ryan Chapin
 # created:  2014-07-06
-# updated:  2015-03-09
-# version:  1.02
+# updated:  2015-03-10
+# version:  1.03
 #
 ################################################################################
 # EXIT CODES:
 #
-# -1 : failed to parse input arguments.
-# -2 : APP argument was not provided or did not parse correctly.
-# -10: wget command failed.
-# -20: checksums did not match
+# 1 : Failed to parse input arguments.
+# 2 : APP argument was not provided or did not parse correctly.
+# 3 : Config file did not provide required variables/were empty.
+# 4 : Required directory did not exist.
+# 10: wget command failed.
+# 20: checksums did not match
 #
+################################################################################
+# FUNCTIONS:
+#
+
+#
+# Debugging and verbose output; accepts two arguments:
+#  $1 = OUTPUT_TYPE [v (verbose) | d (debug) ]
+#  $2 = OUTPUT_MSG
+function output_msg {
+   if [ "v" = "$1" ] && [ 1 -eq "$VERBOSE" ];
+   then
+      echo "$2"
+   fi   
+
+   if [ "d" = "$1" ] && [ 1 -eq "$DEBUG" ];
+   then
+      echo "$2"
+   fi   
+}
+
+#
+# Abstraction for calling wget, supressing its stdout/stderr and checking the
+# exit code from wget.
+# Accepts one argument:
+#  $1 = URL the url to download
+function download_file {
+   local URL=$1
+   CMD="wget $URL"
+   
+   if [ 1 -ne "$VERBOSE" ];
+   then
+      CMD="$CMD > /dev/null 2>&1"
+   fi
+   
+   eval $CMD
+   
+   if [ 0 -ne $? ];
+   then
+      output_msg v "ERROR: Command \'$CMD\' failed"
+      exit 10
+   fi
+}
+
+function dir_exists {
+   DIR_TO_CHECK=$1
+
+   if [ ! -d "$DIR_TO_CHECK" ];
+   then
+      output_msg v "ERROR: Directory, '$DIR_TO_CHECK' does not exist."
+      output_msg v "       Check the aformentioned var in your .conf file."
+      exit 4
+   fi
+}
+
+function var_is_set {
+   VAR_VAL=$1
+   VAR_NAME=$2
+
+   if [ -z "$VAR_VAL" ];
+   then
+      output_msg v "ERROR: Required variable '\$$VAR_NAME' was not set."
+      output_msg v "       Check the aformentioned var in your .conf file."
+      exit 3
+   fi
+}
+
 ################################################################################
 # CONFIGURATIONS:
 #
@@ -70,6 +138,7 @@ SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 # Pull in the user configurations
 source ${SCRIPT_DIR}/${USER_CONF_FILE} 
+
 
 UNPACK_DIR="install_moz_app_temp"
 
@@ -83,6 +152,9 @@ SHA_SUMS_FILE=SHA512SUMS
 SHA_SUMS_URL_PREFIX=https://ftp.mozilla.org/pub/mozilla.org
 SHA_SUMS_URL_SUFFIX=releases/latest/${SHA_SUMS_FILE}
 
+#
+# Configs for 
+#
 
 ################################################################################
 
@@ -163,44 +235,6 @@ UNPACK_PARENT_DIR="/tmp"
 EOF
 }
 
-################################################################################
-# Debugging
-
-# Accepts two arguments:
-#  $1 = OUTPUT_TYPE [v (verbose) | d (debug) ]
-#  $2 = OUTPUT_MSG
-function output_msg {
-   if [ "v" = "$1" ] && [ 1 -eq "$VERBOSE" ];
-   then
-      echo "$2"
-   fi	
-
-   if [ "d" = "$1" ] && [ 1 -eq "$DEBUG" ];
-   then
-      echo "$2"
-   fi	
-}
-
-
-function download_file {
-   local URL=$1
-   CMD="wget $URL"
-   
-   if [ 1 -ne "$VERBOSE" ];
-   then
-      CMD="$CMD > /dev/null 2>&1"
-   fi
-   
-   eval $CMD
-   
-   if [ 0 -ne $? ];
-   then
-      output_msg -v "ERROR: Command \'$CMD\' failed"
-      exit -10
-   fi
-}
-
-################################################################################
 
 HELP=0
 VERBOSE=0
@@ -214,7 +248,7 @@ PARSED_OPTIONS=`getopt -o hvda: -l more-help -- "$@"`
 if [ $? -ne 0 ];
 then
    echo "ERROR: Failed to parse arguments"
-   exit -1
+   exit 1
 fi
 
 eval set -- "$PARSED_OPTIONS"
@@ -271,24 +305,37 @@ then
    exit 0
 fi
 
-#
-# Check that the required arguments were provided
-#
-if [ -z "$APP" ];
-then
-   output_msg v "ERROR: no application key was specified"
-   exit -2
-fi
-
 output_msg d "-a HELP arg = $HELP"
 output_msg d "-a VERBOSE arg = $VERBOSE"
 output_msg d "-a MORE_HELP arg = $MORE_HELP"
 output_msg d "-a DEBUG arg = $DEBUG"
 output_msg d "-a APP arg = $APP"
 
-BINARY_NAME=$APP
+#
+# Check that the required arguments were provided
+#
+if [ -z "$APP" ];
+then
+   output_msg v "ERROR: no application key was specified"
+   exit 2
+fi
 
+#
+# Verify that all of the required configs have been set 
+#
+var_is_set "$OS_VERSION" "OS_VERSION"
+var_is_set "$LANGUAGE" "LANGUAGE"
+
+var_is_set "$INSTALL_DIR" "INSTALL_DIR"
+dir_exists "$INSTALL_DIR"
+
+var_is_set "$UNPACK_PARENT_DIR" "UNPACK_PARENT_DIR"
+dir_exists "$UNPACK_PARENT_DIR"
+
+
+BINARY_NAME=$APP
 output_msg v "Installing mozilla app: $APP"
+
 
 # Concatenate the urls of both the binary to be downloaded and the checksum
 # files to be downloaded
@@ -325,6 +372,7 @@ download_file $WGET_INDEX_URL
 # Dynamically generate the grep command that will pull the file name
 # out of the downloaded html
 #
+# FIXME: Abstract out the specifics for this search, ie the '*.bz2'
 GREP_CMD="grep -oh '${BINARY_NAME}-.*.bz2\"' index.html | sed 's/\"//g'"
 output_msg d "BINARY_NAME GREP_CMD = $GREP_CMD"
 
@@ -378,7 +426,7 @@ SHA_SUM_MATCHED=false
 
 if [ "$SHA_SUM" == "$BZ2_FILE_SHA_SUM" ];
 then
-	SHA_SUM_MATCHED=true
+   SHA_SUM_MATCHED=true
 fi
 output_msg d "SHA_SUM_MATCHED = $SHA_SUM_MATCHED"
 
@@ -389,31 +437,31 @@ if [ "$SHA_SUM_MATCHED" = true ];
 then
    output_msg v "the sha512sums matched, continuing installation...."
 
-	#
-	# Unpack the bz2 file and then rename it to include the version number
-	#
-	output_msg v "Unpacking the ${BZ2_FILE} file"
-	tar -xjf $BZ2_FILE
-	BIN_DIR_W_VERSION=${BINARY_NAME}-${VERSION_NUMBER}
-	mv $BINARY_NAME ${BIN_DIR_W_VERSION}
+   #
+   # Unpack the bz2 file and then rename it to include the version number
+   #
+   output_msg v "Unpacking the ${BZ2_FILE} file"
+   tar -xjf $BZ2_FILE
+   BIN_DIR_W_VERSION=${BINARY_NAME}-${VERSION_NUMBER}
+   mv $BINARY_NAME ${BIN_DIR_W_VERSION}
 
-	#
-	# mv it to the directory into which we are going to install it
-	#
-	output_msg v "Moving the unpacked dir $BIN_DIR_W_VERSION to $INSTALL_DIR"
-	rm -rf $INSTALL_DIR/$BIN_DIR_W_VERSION
-	mv $BIN_DIR_W_VERSION $INSTALL_DIR
+   #
+   # mv it to the directory into which we are going to install it
+   #
+   output_msg v "Moving the unpacked dir $BIN_DIR_W_VERSION to $INSTALL_DIR"
+   rm -rf $INSTALL_DIR/$BIN_DIR_W_VERSION
+   mv $BIN_DIR_W_VERSION $INSTALL_DIR
 
-	#
-	# Updated the symlink
-	#
-	output_msg v "Updating the symlink to point to $BIN_DIR_W_VERSION"
-	cd $INSTALL_DIR
-	ln -sfn $BIN_DIR_W_VERSION $BINARY_NAME
+   #
+   # Updated the symlink
+   #
+   output_msg v "Updating the symlink to point to $BIN_DIR_W_VERSION"
+   cd $INSTALL_DIR
+   ln -sfn $BIN_DIR_W_VERSION $BINARY_NAME
 else
-	output_msg v "The sha512sums did NOT match"
-	output_msg v "Exiting..."
-	exit -20
+   output_msg v "The sha512sums did NOT match"
+   output_msg v "Exiting..."
+   exit 20
 fi
 
 #
@@ -426,4 +474,3 @@ rm -rf $UNPACK_DIR
 cd $START_DIR
 output_msg v "Update of ${BINARY_NAME} complete"
 exit 0
-
